### ISSUE TITLE
Vulkan backend fails to compile on Ubuntu 24.04: 'spv' has not been declared in ggml-vulkan.cpp (SPIRV-Headers)

### ISSUE THREAD

**Issue by TimeToBuildBob** [julianmb/q38rocm#9]
**Environment**: as in #7 (Ubuntu 24.04 LXC, gfx1151), `mesa-vulkan-drivers`/`libvulkan-dev`/`glslang-tools` installed from noble.

With `-DGGML_VULKAN=ON` (the default), compilation fails:

```
engine/src/ggml/src/ggml-vulkan/ggml-vulkan.cpp:2264:33: error: 'spv' has not been declared
 2264 |         uint32_t wc   = word >> spv::WordCountShift;
 2265 |         uint32_t op   = word & spv::OpCodeMask;
```

Looks like `ggml_vk_strip_decode_vector` uses the SPIR-V enum header (`spirv.hpp`) which isn't pulled in on noble's packaged Vulkan headers — likely needs an explicit `spirv-headers` dependency or a vendored include. I worked around it with `-DGGML_VULKAN=OFF` (HIP-only), so this is low priority for the primary use case, but the dual-backend default build is broken on stock Ubuntu 24.04.

Side note for the README: ROCm's apt repo has no Debian 13 support — my first attempt on a Debian 13 container failed at `Failed to find ROCm root directory`; rebuilding the container on Ubuntu 24.04 (noble) with the repo.radeon.com `latest` channel worked cleanly, including inside an **unprivileged LXC** (only `/dev/kfd` + `/dev/dri/renderD128` passed through — might be worth a docs section, happy to draft it).

**Comment by julianmb** [comment]
Fixed in `bcde052`.

The pinned source already has the portable `<spirv/unified1/spirv.hpp>` include path, but Ubuntu needs the separate Khronos headers package. Changes:
- Vulkan builds now preflight the SPIR-V C++ header and fail early with `sudo apt install spirv-headers`
- Ubuntu build dependencies now include `spirv-headers`
- added `./build_engine.sh --rocm-only` (alias `--no-vulkan`) as an explicit HIP-only fallback
- documented that ROCm officially supports Ubuntu 24.04, while AMD does not currently publish a Debian 13 apt repo

Verified against pinned ROCmFPX `0fc9568`: CMake detected Vulkan, generated all shaders, compiled `ggml-vulkan.cpp` (including the `spv::WordCountShift` / `spv::OpCodeMask` code), and linked `libggml-vulkan.a` plus the final `llama-server` successfully.

Thanks for the detailed report and LXC notes.
